version: '2'
services:
    app:
        build:
            context: .
            dockerfile: dockerfile.dev
        command: yarn dev
        volumes: 
            - .:/usr/app
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        restart: always
        environment: 
            PORT: 3000
            MONGO_URL: "mongodb://mongodb/test"
            SESSION_TIME: 1000
            SECRET: "TESTTEST"
        depends_on: 
            - mongodb
    mongodb:
        image: mongo
        restart: always
        ports:
            - "4000:27017"